pull_request_rules:
  - name: automatic merge rodo's PR on main
    conditions:
      - author=rodo
      - check-success=build
      - check-success=unittest
      - check-success=postgresql
      - base=main
    actions:
      merge:
        method: merge
