queue_rules:
  - name: hotfix
    queue_conditions:
      - label = hotfix
  - name: standard

pull_request_rules:
  - name: put PRs in queue
    conditions:
      - and:
          - base=main
          - check-success=unittest
    actions:
      queue:
