queue_rules:
  - name: hotfix
    queue_conditions:
      - label = hotfix
  - name: standard

pull_request_rules:
  - name: add lablel when author is rodo
    conditions:
      - author = rodo
    actions:
      label:
        add:
          - Rodolphe

  - name: put PRs in queue
    conditions:
      - base=main
      - check-success=build
      - check-success=unittest
      - check-success=postgresql

    actions:
      merge:
        method: merge
