queue_rules:
  - name: hotfix
    queue_conditions:
      - label = hotfix
  - name: standard

pull_request_rules:
  - name: put PRs in queue
    conditions:
      - base=main
      - check-success=build
      - check-success=unittest
      - check-success=postgresql

    actions:
      merge:
        method: merge
