# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: postgresql

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: create db source
      run: psql "postgres://postgres:postgres@localhost:5432/postgres" -c 'CREATE DATABASE source'

    - name: create db destination
      run: psql "postgres://postgres:postgres@localhost:5432/postgres" -c 'CREATE DATABASE destination'

    - name: create structure source
      run: psql "postgres://postgres:postgres@localhost:5432/source" -f data_test/tables.sql

    - name: create structure destination
      run: psql "postgres://postgres:postgres@localhost:5432/destination" -f data_test/tables.sql

    - name: fill db source
      run: psql "postgres://postgres:postgres@localhost:5432/source" -f data_test/data.sql

    - name: run tests
      run: ./expulo
      env:
        PGSRCHOST: localhost
        PGSRCPORT: 5432
        PGSRCUSER: postgres
        PGSRCPASSWORD: postgres
        PGSRCDATABASE: source
        PGDSTHOST: localhost
        PGDSTPORT: 5432
        PGDSTUSER: postgres
        PGDSTPASSWORD: postgres
        PGDSTDATABASE: destination
